inherit: true
filter:
    excluded_paths:
        - 'vendor/**'
        - 'fuel-core/*'
        - 'packages/*'
        - 'framework/vendor/*'
        - 'static/admin/vendor/*'
        - 'static/admin/bundle/*'
